### ISSUE TITLE
vangers_server segfault

### ISSUE THREAD

**Issue by caiiiycuk** [KranX/Vangers#478]
```
Core was generated by `./vangers_server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007fd454bdee39 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00005625fbfaf1ff in Server::analyse_statistics (this=0x5625fd1de3c0, g=0x5625fd2292e0) at /root/Vangers/server/server.cpp:1858
#3  0x00005625fbfaee21 in Server::games_quant (this=0x5625fd1de3c0) at /root/Vangers/server/server.cpp:1814
#4  0x00005625fbfaed7c in Server::quant (this=0x5625fd1de3c0) at /root/Vangers/server/server.cpp:1803
#5  0x00005625fbfa6c06 in KDsPlus::Quant (this=0x5625fd1de6d0) at /root/Vangers/server/kdsplus.cpp:92
#6  0x00005625fbfb344f in main (argc=1, argv=0x7fff4c6a54d8) at /root/Vangers/lib/xtool/xtcore.cpp:222
```

**Comment by caiiiycuk** [comment]
[Uploading dump.zip…]()

**Comment by caiiiycuk** [comment]
[dump.zip](https://github.com/KranX/Vangers/files/6680896/dump.zip)

**Comment by caiiiycuk** [comment]
Перед смертью сервер написал
```
Games: 0 Players: 0 Clients: 0
Games: 1 Players: 1 Clients: 0

Games' Statistics (maximum/average):
VAN_WAR: 1; Players: 2/1; Time of game: 6/5 min.
Segmentation fault (core dumped)
```
