### ISSUE TITLE
Краш при старте игры

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#480]
Крашится где-то каждый второй или третий раз при запуске, ещё до загрузки главного меню. Где-то последние года два точно. На других ПК, впрочем, почему-то такого у меня не было, только на моём обычном...

```
Thread 8 "SDLAudioP1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd9a34700 (LWP 9227)]
0x00007ffff75b88d8 in clunk::Object::DistanceOrder::DistanceOrder(clunk::v3<float> const&) () from /usr/local/lib/libclunk.so
(gdb) bt
#0  0x00007ffff75b88d8 in clunk::Object::DistanceOrder::DistanceOrder(clunk::v3<float> const&) () at /usr/local/lib/libclunk.so
#1  0x00007ffff75b69f9 in clunk::Context::process(short*, int) ()
    at /usr/local/lib/libclunk.so
#2  0x00007ffff75b6932 in clunk::Context::callback(void*, unsigned char*, int)
    () at /usr/local/lib/libclunk.so
#3  0x00007ffff7ac1d35 in  () at /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x00007ffff7b08d7c in  () at /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#5  0x00007ffff7b7e0f9 in  () at /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#6  0x00007ffff1e4d6db in start_thread (arg=0x7fffd9a34700)
    at pthread_create.c:463
#7  0x00007ffff44c571f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Aidoneus** [comment]
Всё ещё актуально (воспроизводится у меня на любом ПК с Debian/Ubuntu)

**Comment by Fenex** [comment]
Устройство вывода звука есть на машине?

**Comment by Aidoneus** [comment]
Да, конечно

**Comment by lpenguin** [comment]
@Aidoneus можешь еще лог игры приложить? Интересно не пишутся ли там ошибки инициализации

**Comment by lpenguin** [comment]
@Aidoneus можешь собрать clunk из этой ветки? https://github.com/lpenguin/clunk/pull/1
